spring:
  datasource:
    url: jdbc:mysql://root:root@localhost:3306/fornecedor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
  flyway:
    baseline-on-migrate: true
